export enum PriceModificationType {
    PRESALE = 'PRESALE',
    REGULAR_SALE = 'REGULAR_SALE',
    DISCOUNT = 'DISCOUNT',
    PROMOTION = 'PROMOTION',
    SPECIAL_OFFER = 'SPECIAL_OFFER',
    GROUP_DISCOUNT = 'GROUP_DISCOUNT',
    EARLY_BIRD = 'EARLY_BIRD'
}