import * as Joi from 'joi';

export const envSchema = Joi.object({
  PORT: Joi.number().default(3000),
  DB_PORT: Joi.number().default(5433),
  DB_HOST: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  DB_USER: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  SECRET_KEY_JWT: Joi.string().required(),
  STRIPE_KEY: Joi.string().required(),
  CLOUDINARY_CLOUD_NAME: Joi.string().required(),
  CLOUDINARY_API_KEY: Joi.string().required(),
  CLOUDINARY_API_SECRET: Joi.string().required(),
  STRIPE_TICKET_WEBHOOK_SECRET: Joi.string().required(),
  STRIPE_TENANT_WEBHOOK_SECRET: Joi.string().required(),
  FRONTEND_URL: Joi.string().uri().required(),
  // BLOCKCHAIN_URL: Joi.string().required(),
  // WALLET_PRIVATE_KEY: Joi.string().required(),
  // HARDHAT_MICROSERVICE_URL: Joi.string().required(),
  // PINATA_API_KEY: Joi.string().required(),
  // PINATA_API_SECRET: Joi.string().required(),
  // AWS_ACCESS_KEY_ID: Joi.string().required(),
  // AWS_SECRET_ACCESS_KEY: Joi.string().required(),
  // AWS_REGION: Joi.string().required(),
  // COHERE_API_KEY: Joi.string().required(),
})